FROM ubuntu:latest

LABEL maintainer="canghailan@gmail.com"

WORKDIR /workspace/
COPY supervisord.conf /etc/supervisor/conf.d/
COPY worker.cgi /usr/lib/cgi-bin/

RUN apt-get update \
 && apt-get install -y curl unzip fontconfig supervisor apache2 imagemagick openjdk-8-jre-headless libglu1-mesa libxinerama1 libdbus-glib-1-2 libcairo2 libsm6 fonts-arphic-* \
 && echo "install fonts" \
 && mkdir -p /tmp/fonts/ /usr/share/fonts/truetype /usr/share/fonts/opentype \
 && echo "download source-sans-pro" \
 && curl -o /usr/share/fonts/opentype/SourceSansVariable-Italic.otf -OL 'http://localhost/SourceSansVariable-Italic.otf' \
 && curl -o /usr/share/fonts/opentype/SourceSansVariable-Roman.otf -OL 'http://localhost/SourceSansVariable-Roman.otf' \
 && echo "download source-serif-pro" \
 && curl -o /usr/share/fonts/opentype/SourceSerifVariable-Roman.otf -OL 'http://localhost/SourceSerifVariable-Roman.otf' \
 && echo "download source-code-pro" \
 && curl -o /usr/share/fonts/opentype/SourceCodeVariable-Roman.otf -OL 'http://localhost/SourceCodeVariable-Roman.otf' \
 && curl -o /usr/share/fonts/opentype/SourceCodeVariable-Italic.otf -OL 'http://localhost/SourceCodeVariable-Italic.otf' \
 && echo "download source-han-sans" \
 && curl -o /tmp/fonts/SourceHanSansSC.zip -OL 'http://localhost/SourceHanSansSC.zip' \
 && curl -o /tmp/fonts/SourceHanSansTC.zip -OL 'http://localhost/SourceHanSansTC.zip' \
 && curl -o /tmp/fonts/SourceHanSansJ.zip -OL 'http://localhost/SourceHanSansJ.zip' \
 && curl -o /tmp/fonts/SourceHanSansK.zip -OL 'http://localhost/SourceHanSansK.zip' \
 && echo "download source-han-serif" \
 && curl -o /tmp/fonts/SourceHanSerifSC_EL-M.zip -OL 'http://localhost/SourceHanSerifSC_EL-M.zip' \
 && curl -o /tmp/fonts/SourceHanSerifSC_SB-H.zip -OL 'http://localhost/SourceHanSerifSC_SB-H.zip' \
 && curl -o /tmp/fonts/SourceHanSerifTC_EL-M.zip -OL 'http://localhost/SourceHanSerifTC_EL-M.zip' \
 && curl -o /tmp/fonts/SourceHanSerifTC_SB-H.zip -OL 'http://localhost/SourceHanSerifTC_SB-H.zip' \
 && curl -o /tmp/fonts/SourceHanSerifJ_EL-M.zip -OL 'http://localhost/SourceHanSerifJ_EL-M.zip' \
 && curl -o /tmp/fonts/SourceHanSerifJ_SB-H.zip -OL 'http://localhost/SourceHanSerifJ_SB-H.zip' \
 && curl -o /tmp/fonts/SourceHanSerifK_EL-M.zip -OL 'http://localhost/SourceHanSerifK_EL-M.zip' \
 && curl -o /tmp/fonts/SourceHanSerifK_SB-H.zip -OL 'http://localhost/SourceHanSerifK_SB-H.zip' \
 && echo "download noto-emoji" \
 && curl -o /usr/share/fonts/truetype/NotoEmoji-Regular.ttf -OL 'http://localhost/NotoEmoji-Regular.ttf' \
 && curl -o /usr/share/fonts/truetype/NotoColorEmoji.ttf -OL 'http://localhost/NotoColorEmoji.ttf' \
 && echo "install fonts" \
 && unzip "/tmp/fonts/*.zip" -d /tmp/fonts/ \
 && find /tmp/fonts/ -name "*.otf" | xargs -I {} cp {} /usr/share/fonts/opentype \
 && fc-cache -fv \
 && echo "install LibreOffice" \
 && curl -o /tmp/LibreOffice.tar.gz -OL 'http://localhost/LibreOffice_6.0.2_Linux_x86-64_deb.tar.gz' \
 && tar -xzvf /tmp/LibreOffice.tar.gz -C /tmp/ \
 && dpkg -i /tmp/LibreOffice*/DEBS/*.deb \
 && echo "install pandoc" \
 && curl -o /tmp/pandoc.deb -OL 'http://localhost/pandoc-2.1.2-1-amd64.deb' \
 && dpkg -i /tmp/pandoc.deb \
 && echo "install unoconv" \
 && curl -o /usr/local/bin/unoconv -OL 'http://localhost/unoconv' \
 && chmod a+x /usr/local/bin/unoconv \
 && echo "configure apache" \
 && mkdir -p /etc/apache2/logs/ \
 && cp -f /etc/apache2/mods-available/cgi.load /etc/apache2/mods-enabled/ \
 && chmod a+x /usr/lib/cgi-bin/worker.cgi \
 && echo "configure supervisord" \
 && mkdir -p /var/log/supervisor/ \
 && echo "make workspace" \
 && chmod a+rwx /workspace/ \
 && ln -s /workspace /var/www/html/ \
 && echo "clean" \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/*

EXPOSE 80
CMD ["/usr/bin/supervisord"]